server:
  port: 3344
spring:
  application:
    name: spring-cloud-config-server-3344
  #连接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Lengxiaochi/springcloudlearn.git  #https